version: '3'

networks:
  whaticket:

services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_HOSTS=whaticketdb
    ports:
      - ${PMA_PORT:-9000}:80
    networks:
      - whaticket